# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'customizedStarRating' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for customizedStarRating
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'Core', 'DevSupport'
  ]
  
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  

  target 'customizedStarRatingTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'customizedStarRating-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for customizedStarRating-tvOS

end
